on: [push,pull_request]

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10.3'
        cache: 'poetry'
    - run: poetry install

